---
- name: Install archiso, et. al.
  become: true
  become_user: root
  package:
    name:
      - git
      - make
      - arch-install-scripts
      - squashfs-tools
      - libisoburn
      - dosfstools
      - lynx
      - archiso
    state: present
- name: Add additional package maintainer keys to your web of trust
  become: true
  become_user: root
  with_items: '{{ archiso_keys_to_trust }}'
  ansible.builtin.command: pacman-key -r '{{ item.keyid }}'
  changed_when: false
- name: Sign additional package maintainer keys
  become: true
  become_user: root
  with_items: '{{ archiso_keys_to_trust }}'
  ansible.builtin.command: pacman-key --lsign-key '{{ item.keyid }}'
  changed_when: false
- name: Copy profile...
  become: true
  become_user: root
  ansible.builtin.command: cp -R -p /usr/share/archiso/configs/{{ archiso_profile }} '{{ archiso_rootdir }}'
  changed_when: false
- name: Add pacman repositories
  become: true
  become_user: root
  with_items: '{{ archiso_pacman_repos }}'
  ansible.builtin.blockinfile:
    path: '{{ archiso_pacman_conf_file }}'
    block: '{{ item }}'
    state: present
- name: Construct packages.*....
  become: true
  become_user: root
  with_items:
    - packages.both
    - packages.i686
    - packages.x86_64
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ archiso_target_dir }}/{{ item }}'
    mode: '644'
- name: Mkdir /etc/ssh
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ archiso_etc_dir }}/ssh'
    state: directory
- name: Copy sshd_config
  become: true
  become_user: root
  ansible.builtin.copy:
    src: /etc/ssh/sshd_config
    dest: '{{ archiso_etc_dir }}/ssh/sshd_config'
    mode: '644'
